# Generated by Django 5.0.7 on 2024-08-02 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shrote_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='response',
            new_name='response_text',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='transcript',
            new_name='user_input',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='language',
        ),
    ]
